metadata:
  resourceType: APPLICATION
  name: graphql
  description: graphql 서버 애플리케이션
spec:
  githubUrl: https://github.com/dolong2/spring_graphql_practice.git
  applicationType: SPRING_BOOT
  port: 8080
  version: 11
  initialScripts:
    - 'echo $GRAPHQL_CONFIG > graphql.config.yml'
    - 'echo $GRAPHQL_SCHEMA > schema.graphqls'
    - 'echo $GRAPHQL_RESPONSE_SCHEMA > response.graphqls'
    - 'echo $GRAPHQL_TOPIC_SCHEMA > topic.graphqls'
    - 'echo $GRAPHQL_POSTING_SCHEMA > posting.graphqls'
    - 'echo $GRAPHQL_MEMBER_SCHEMA > member.graphqls'
    - 'echo $GRAPHQL_COMMENT_SCHEMA > comment.graphqls'
  labels:
    - graphql